-- 1. Delete from DELIVERIES first (depends on ORDERS)
DELETE FROM DELIVERIES WHERE ORDER_ID = 1;

-- 2. Delete from PAYMENTS (depends on ORDERS)
DELETE FROM PAYMENTS WHERE ORDER_ID = 1;

-- 3. Delete from ORDER_ITEMS (depends on ORDERS and MENU)
DELETE FROM ORDER_ITEMS WHERE ORDER_ID = 1;

-- 4. Delete from ORDERS (depends on USERS and RESTAURANT)
DELETE FROM ORDERS WHERE ORDER_ID = 1;

-- 5. Delete from MENU (depends on RESTAURANT)
DELETE FROM MENU WHERE MENU_ITEM_ID = 1;

-- 6. Delete from RESTAURANT (depends on USERS)
DELETE FROM RESTAURANT WHERE RESTAURANT_ID = 1;

-- 7. Finally, delete the USER
DELETE FROM USERS WHERE USER_ID = 1;
