CREATE TABLE DELIVERIES (
    DELIVERY_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    DRIVER_ID INT NOT NULL,
    DELIVERY_STATUS ENUM('ASSIGNED','PICKED_UP','IN_TRANSIT','DELIVERED','FAILED') DEFAULT 'ASSIGNED',
    ESTIMATED_TIME TIMESTAMP,
    ACTUAL_TIME TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);