USE restaurant_ordering;

DELIMITER //

CREATE TRIGGER TRIGGER_NEW_DELIVERY
BEFORE INSERT ON DELIVERIES
FOR EACH ROW
BEGIN
    -- Fixed platform cut
    SET NEW.DELIVERY_PLATFORM_CUT = 2.00;

    -- Optional safety
    IF NEW.DELIVERY_FEE_TOTAL IS NULL THEN
        SET NEW.DELIVERY_FEE_TOTAL = 0.00;
    END IF;
END //
