USE restaurant_ordering;

CREATE OR REPLACE VIEW INVESTOR_PROFIT_VIEW AS
SELECT
    o.ORDER_ID,
    r.RESTAURANT_NAME,
    o.ORDER_DATE,
    o.PLATFORM_COMMISSION,
    o.SERVICE_FEE,
    d.DELIVERY_PLATFORM_CUT,
    (o.PLATFORM_PROFIT_ORDER + d.DELIVERY_PLATFORM_CUT) AS TOTAL_PLATFORM_PROFIT
FROM ORDERS o
LEFT JOIN RESTAURANT r ON o.RESTAURANT_ID = r.RESTAURANT_ID
LEFT JOIN DELIVERIES d ON o.ORDER_ID = d.ORDER_ID;
