CREATE TABLE MENU(
MENU_ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
ITEM_NAME VARCHAR(30) NOT NULL, 
ITEM_DESCRIP VARCHAR(200) NULL,
PRICE DECIMAL(7,2) NOT NULL,
RESTAURANT_ID INT NOT NULL,
FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID)
);