DELIMITER //

CREATE TRIGGER TRIGGER_ORDER_COMPLETE
AFTER UPDATE ON ORDERS
FOR EACH ROW
BEGIN
    -- If order status changed to Completed
    IF NEW.STATUS = 'Completed' AND OLD.STATUS <> 'Completed' THEN
        CALL CALCULATE_ORDER_PROFIT(NEW.ORDER_ID);
    END IF;
END //

DELIMITER ;

