CREATE TABLE PAYMENTS (
    PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    METHOD ENUM('CREDIT_CARD','DEBIT_CARD','PAYPAL','CASH') NOT NULL,
    STATUS ENUM('PENDING','COMPLETED','FAILED','REFUNDED') DEFAULT 'PENDING',
    PAYMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);