CREATE TABLE RESTAURANT(
RESTAURANT_ID INT AUTO_INCREMENT PRIMARY KEY,
RESTAURANT_NAME VARCHAR(100) NOT NULL,
ADDRESS VARCHAR (100) NOT NULL,
PHONE VARCHAR(50) NOT NULL,
OWNER_ID INT NOT NULL,
FOREIGN KEY (OWNER_ID) REFERENCES USERS(USER_ID)
);