CREATE TABLE RESTAURANT(
RESTAURANT_ID INT AUTO_INCREMENT PRIMARY KEY,
OWNER_ID INT NOT NULL,
RESTAURANT_NAME VARCHAR(100) NOT NULL,
BUILDING_NUMBER INT,
STREET VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(50),
ZIPCODE INT,
PHONE VARCHAR(50),
FOREIGN KEY (OWNER_ID) REFERENCES USERS(USER_ID)
);
