-- Use the project database
CREATE DATABASE IF NOT EXISTS restaurant_ordering;
USE restaurant_ordering;


-- USERS TABLE
CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    PASS_WORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20) UNIQUE NOT NULL,
    ROLES ENUM('customer','restaurant_owner','driver') NOT NULL,
    ACCOUNT_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- RESTAURANT TABLE
CREATE TABLE RESTAURANT (
	RESTAURANT_ID INT AUTO_INCREMENT PRIMARY KEY,
	OWNER_ID INT NOT NULL,
	RESTAURANT_NAME VARCHAR(100) NOT NULL,
	BUILDING_NUMBER INT,
	STREET VARCHAR(100),
	CITY VARCHAR(100),
	STATE VARCHAR(50),
	ZIPCODE INT,
	PHONE VARCHAR(50),
	FOREIGN KEY (OWNER_ID) REFERENCES USERS(USER_ID)
);


-- MENU TABLE
CREATE TABLE MENU (
    MENU_ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM_NAME VARCHAR(30) NOT NULL,
    ITEM_DESCRIP VARCHAR(200),
    PRICE DECIMAL(7,2) NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID)
);


-- ORDERS TABLE
CREATE TABLE ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS ENUM('PENDING','CONFIRMED','PREPARING','OUT_FOR_DELIVERY','DELIVERED','CANCELLED') DEFAULT 'PENDING',
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
	PLATFORM_COMMISSION DECIMAL(10,2),
	SERVICE_FEE DECIMAL(10,2),
	PLATFORM_PROFIT_ORDER DECIMAL(10,2),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID)
);


-- ORDER_ITEMS TABLE
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    MENU_ITEM_ID INT NOT NULL,
    QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
    PRICE DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU(MENU_ITEM_ID)
);


-- PAYMENTS TABLE
CREATE TABLE PAYMENTS (
    PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    METHOD ENUM('CREDIT_CARD','DEBIT_CARD','PAYPAL','CASH') NOT NULL,
    STATUS ENUM('PENDING','COMPLETED','FAILED','REFUNDED') DEFAULT 'PENDING',
    PAYMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);


-- DELIVERIES TABLE
CREATE TABLE DELIVERIES (
    DELIVERY_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    DRIVER_ID INT NOT NULL,
    DELIVERY_STATUS ENUM('ASSIGNED','PICKED_UP','IN_TRANSIT','DELIVERED','FAILED') DEFAULT 'ASSIGNED',
    ESTIMATED_TIME TIMESTAMP,
    ACTUAL_TIME TIMESTAMP,
    DELIVERY_FEE_TOTAL DECIMAL(10,2),
	DELIVERY_PLATFORM_CUT DECIMAL(10,2),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (DRIVER_ID) REFERENCES USERS(USER_ID)
);
