CREATE TABLE USERS(
USER_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_NAME VARCHAR(100) NOT NULL,
PASS_WORD VARCHAR(100) NOT NULL, 
EMAIL VARCHAR(100) UNIQUE NOT NULL,
PHONE VARCHAR(20) UNIQUE NOT NULL, 
ROLES ENUM('customer', 'restaurant_owner', 'driver', 'investor') NOT NULL,
ACCOUNT_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
