// mock data for development

import { Restaurant, MenuItem } from "./types";

export const mockRestaurants: Restaurant[] = [
  {
    id: 1,
    name: "FUMO Harlem",
    cuisine: "Italian",
    description: "Modern Italian cuisine with wood-fired pizzas and fresh pasta",
    rating: 4.6,
    deliveryTime: "25-35 min",
    deliveryFee: 3.99,
    image: "/images/fumo.jpeg",
    isOpen: true,
  },
  {
    id: 2,
    name: "Cafe One",
    cuisine: "Caribbean",
    description: "Authentic Caribbean flavors with jerk chicken and oxtail",
    rating: 4.5,
    deliveryTime: "30-40 min",
    deliveryFee: 2.99,
    image: "/images/cafe_one.avif",
    isOpen: true,
  },
  {
    id: 3,
    name: "Burger & Shake Co",
    cuisine: "American",
    description: "Gourmet burgers and hand-spun milkshakes",
    rating: 4.4,
    deliveryTime: "20-30 min",
    deliveryFee: 2.49,
    image: "/images/burger_and_shake.jpg",
    isOpen: true,
  },
  {
    id: 4,
    name: "Bricola Harlem",
    cuisine: "Italian",
    description: "Rustic Italian dining with handmade pasta and seasonal dishes",
    rating: 4.7,
    deliveryTime: "30-40 min",
    deliveryFee: 4.49,
    image: "/images/briccola.jpg",
    isOpen: true,
  },
  {
    id: 5,
    name: "Charles Pan Fried Chicken",
    cuisine: "Southern",
    description: "Legendary soul food with crispy fried chicken and classic sides",
    rating: 4.8,
    deliveryTime: "25-35 min",
    deliveryFee: 3.49,
    image: "/images/charles_panfried_chicken.webp",
    isOpen: true,
  },
  {
    id: 6,
    name: "Clove",
    cuisine: "American",
    description: "Farm-to-table American cuisine with seasonal ingredients",
    rating: 4.6,
    deliveryTime: "35-45 min",
    deliveryFee: 3.99,
    image: "/images/clove.webp",
    isOpen: false,
  },
];

export const mockMenuItems: MenuItem[] = [
  // FUMO Harlem Menu
  {
    id: 1,
    restaurantId: 1,
    name: "Margherita Pizza",
    description: "San Marzano tomatoes, fresh mozzarella, basil",
    price: 16.99,
    category: "Pizza",
    image: "/images/food/margherita.webp",
    available: true,
  },
  {
    id: 2,
    restaurantId: 1,
    name: "Prosciutto e Arugula Pizza",
    description: "Prosciutto di Parma, arugula, shaved parmesan",
    price: 19.99,
    category: "Pizza",
    image: "/images/food/pros.jpg",
    available: true,
  },
  {
    id: 3,
    restaurantId: 1,
    name: "Rigatoni Bolognese",
    description: "Slow-cooked meat ragu with fresh rigatoni",
    price: 18.99,
    category: "Pasta",
    image: "/images/food/rigatoni.webp",
    available: true,
  },
  {
    id: 4,
    restaurantId: 1,
    name: "Burrata & Tomatoes",
    description: "Creamy burrata with heirloom tomatoes and basil",
    price: 14.99,
    category: "Appetizers",
    image: "/images/food/burrata.jpg",
    available: true,
  },

  // Cafe One Menu
  {
    id: 5,
    restaurantId: 2,
    name: "Jerk Chicken Plate",
    description: "Spicy jerk chicken with rice and peas",
    price: 13.99,
    category: "Entrees",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 6,
    restaurantId: 2,
    name: "Oxtail Stew",
    description: "Tender braised oxtail with butter beans",
    price: 16.99,
    category: "Entrees",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 7,
    restaurantId: 2,
    name: "Curry Goat",
    description: "Authentic Caribbean curry goat with rice",
    price: 14.99,
    category: "Entrees",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 8,
    restaurantId: 2,
    name: "Fried Plantains",
    description: "Sweet ripe plantains fried to perfection",
    price: 5.99,
    category: "Sides",
    image: "/placeholder-food.jpg",
    available: true,
  },

  // Burger & Shake Co Menu
  {
    id: 9,
    restaurantId: 3,
    name: "Classic Burger",
    description: "Beef patty, lettuce, tomato, onion, special sauce",
    price: 10.99,
    category: "Burgers",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 10,
    restaurantId: 3,
    name: "BBQ Bacon Burger",
    description: "Beef patty, crispy bacon, cheddar, BBQ sauce",
    price: 12.99,
    category: "Burgers",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 11,
    restaurantId: 3,
    name: "Chocolate Milkshake",
    description: "Hand-spun chocolate shake with whipped cream",
    price: 6.99,
    category: "Shakes",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 12,
    restaurantId: 3,
    name: "Loaded Fries",
    description: "Crispy fries topped with cheese, bacon, and ranch",
    price: 7.99,
    category: "Sides",
    image: "/placeholder-food.jpg",
    available: true,
  },

  // Bricola Harlem Menu
  {
    id: 13,
    restaurantId: 4,
    name: "Pappardelle al Ragu",
    description: "Wide ribbon pasta with slow-cooked meat sauce",
    price: 22.99,
    category: "Pasta",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 14,
    restaurantId: 4,
    name: "Osso Buco",
    description: "Braised veal shanks with gremolata",
    price: 28.99,
    category: "Entrees",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 15,
    restaurantId: 4,
    name: "Arancini",
    description: "Crispy risotto balls with marinara",
    price: 11.99,
    category: "Appetizers",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 16,
    restaurantId: 4,
    name: "Tiramisu",
    description: "Classic Italian dessert with espresso and mascarpone",
    price: 9.99,
    category: "Desserts",
    image: "/placeholder-food.jpg",
    available: true,
  },

  // Charles Pan Fried Chicken Menu
  {
    id: 17,
    restaurantId: 5,
    name: "Fried Chicken Dinner",
    description: "Three pieces of golden pan-fried chicken",
    price: 14.99,
    category: "Entrees",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 18,
    restaurantId: 5,
    name: "Chicken & Waffles",
    description: "Crispy chicken with Belgian waffles and syrup",
    price: 16.99,
    category: "Entrees",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 19,
    restaurantId: 5,
    name: "Mac & Cheese",
    description: "Creamy homemade mac and cheese",
    price: 6.99,
    category: "Sides",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 20,
    restaurantId: 5,
    name: "Collard Greens",
    description: "Slow-cooked collard greens with smoked turkey",
    price: 5.99,
    category: "Sides",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 21,
    restaurantId: 5,
    name: "Candied Yams",
    description: "Sweet candied yams with brown sugar glaze",
    price: 5.99,
    category: "Sides",
    image: "/placeholder-food.jpg",
    available: true,
  },

  // Clove Menu
  {
    id: 22,
    restaurantId: 6,
    name: "Grilled Salmon",
    description: "Atlantic salmon with seasonal vegetables and quinoa",
    price: 24.99,
    category: "Entrees",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 23,
    restaurantId: 6,
    name: "Grass-Fed Burger",
    description: "House-ground beef with aged cheddar and caramelized onions",
    price: 17.99,
    category: "Burgers",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 24,
    restaurantId: 6,
    name: "Kale Caesar Salad",
    description: "Fresh kale with house-made Caesar dressing and croutons",
    price: 12.99,
    category: "Salads",
    image: "/placeholder-food.jpg",
    available: true,
  },
  {
    id: 25,
    restaurantId: 6,
    name: "Truffle Fries",
    description: "Hand-cut fries with truffle oil and parmesan",
    price: 8.99,
    category: "Sides",
    image: "/placeholder-food.jpg",
    available: true,
  },
];

export function getRestaurantById(id: number): Restaurant | undefined {
  return mockRestaurants.find((r) => r.id === id);
}

export function getMenuItemsByRestaurant(restaurantId: number): MenuItem[] {
  return mockMenuItems.filter((item) => item.restaurantId === restaurantId);
}