CREATE TABLE MENU(
MENU_ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
ITEM_NAME VARCHAR(30) NOT NULL, 
ITEM_DESCRIP VARCHAR(200) NULL,
PRICE DECIMAL(7,2) NOT NULL,
RESTAURANT_ID INT NOT NULL,
FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID)
);

-- RESETS
DELETE FROM MENU;
DELETE FROM RESTAURANT;
ALTER TABLE RESTAURANT AUTO_INCREMENT = 1;
ALTER TABLE MENU AUTO_INCREMENT = 1;

-- TEST 1 - TESTING FOREIGN KEY (SHOULD FAIL)
INSERT INTO MENU (ITEM_NAME, ITEM_DESCRIP, PRICE, RESTAURANT_ID)
VALUES ('Ghost Sandwich', 'Does not exist', 9.99, 999);

-- RESET
DELETE FROM MENU;
DELETE FROM RESTAURANT;
DELETE FROM USERS;

ALTER TABLE USERS AUTO_INCREMENT = 1;
ALTER TABLE RESTAURANT AUTO_INCREMENT = 1;
ALTER TABLE MENU AUTO_INCREMENT = 1;

-- TEST 2 - INSERTING VALUES
INSERT INTO USERS (USER_NAME, PASS_WORD, EMAIL, PHONE, ROLES)
VALUES 
('Alice', 'pwd1', 'alice@example.com', '1111111111', 'restaurant_owner'),
('Bob', 'pwd2', 'bob@example.com', '2222222222', 'restaurant_owner');

INSERT INTO RESTAURANT (RESTAURANT_NAME, ADDRESS, PHONE, OWNER_ID)
VALUES
('Alice Cafe', '123 Main St', '555-1111', 1),
('Bob Burgers', '456 Oak Rd', '555-2222', 2);

INSERT INTO MENU (ITEM_NAME, ITEM_DESCRIP, PRICE, RESTAURANT_ID)
VALUES 
('Espresso', 'Strong black coffee', 2.50, 1),
('Cappuccino', 'Coffee with milk foam', 3.00, 1),
('Cheeseburger', 'Beef burger with cheese', 5.99, 2);

SELECT * FROM MENU;

DELETE FROM MENU;
DELETE FROM RESTAURANT;
DELETE FROM USERS;

ALTER TABLE USERS AUTO_INCREMENT = 1;
ALTER TABLE RESTAURANT AUTO_INCREMENT = 1;
ALTER TABLE MENU AUTO_INCREMENT = 1;

-- TEST 3 - TESTING FOREIGN KEY
INSERT INTO USERS (USER_NAME, PASS_WORD, EMAIL, PHONE, ROLES)
VALUES 
('Alice', 'pwd1', 'alice@example.com', '1111111111', 'restaurant_owner'),
('Bob', 'pwd2', 'bob@example.com', '2222222222', 'restaurant_owner');

INSERT INTO RESTAURANT (RESTAURANT_NAME, ADDRESS, PHONE, OWNER_ID)
VALUES
('Alice Cafe', '123 Main St', '555-1111', 1),
('Bob Burgers', '456 Oak Rd', '555-2222', 2);

INSERT INTO MENU (ITEM_NAME, ITEM_DESCRIP, PRICE, RESTAURANT_ID)
VALUES
('Espresso', 'Small strong coffee', 2.50, 1),
('Cheeseburger', 'Classic beef burger with cheese', 5.99, 2);

SELECT * FROM RESTAURANT;
SELECT * FROM MENU;
