CREATE TABLE RESTAURANT(
RESTAURANT_ID INT AUTO_INCREMENT PRIMARY KEY,
RESTAURANT_NAME VARCHAR(100) NOT NULL,
ADDRESS VARCHAR (100) NOT NULL,
PHONE VARCHAR(50) NOT NULL,
OWNER_ID INT NOT NULL,
FOREIGN KEY (OWNER_ID) REFERENCES USERS(USER_ID)
);

-- TEST1 - INSERTING DATA
INSERT INTO USERS (USER_NAME, PASS_WORD, EMAIL, PHONE, ROLES)
VALUES 
('Alice Johnson', 'hashed_pwd1', 'alice@example.com', '1234567890', 'restaurant_owner'),
('Bob Smith', 'hashed_pwd2', 'bob@example.com', '0987654321', 'restaurant_owner'),
('Charlie Lee', 'hashed_pwd3', 'charlie@example.com', '1112223333', 'customer'),
('David Ray', 'hashed_pwd4', 'david@example.com', '2223334444', 'driver');

INSERT INTO RESTAURANT (RESTAURANT_NAME, ADDRESS, PHONE, OWNER_ID)
VALUES 
('Alice\'s Cafe', '123 Main St', '555-1234', 1),
('Bob\'s Burgers', '456 Oak Rd', '555-5678', 2);

SELECT * FROM RESTAURANT;

-- TEST2 - FOREIGN KEY SHOULD SUCCEED
INSERT INTO RESTAURANT (RESTAURANT_NAME, ADDRESS, PHONE, OWNER_ID)
VALUES ('Bob\'s Pizza', '789 Pine St', '555-9876', 2); 

SELECT * FROM RESTAURANT;

-- TEST3 - FOREIGN KEY SHOULD FAIL
INSERT INTO RESTAURANT (RESTAURANT_NAME, ADDRESS, PHONE, OWNER_ID)
VALUES ('Ghost Cafe', '999 Nowhere St', '000-0000', 999);

TRUNCATE TABLE RESTAURANT;
ALTER TABLE RESTAURANT AUTO_INCREMENT = 1;
