CREATE DATABASE TEST_RESTAURANT;
USE TEST_RESTAURANT;

CREATE TABLE USERS(
USER_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_NAME VARCHAR(100) NOT NULL,
PASS_WORD VARCHAR(100) NOT NULL, 
EMAIL VARCHAR(100) UNIQUE NOT NULL,
PHONE VARCHAR(20) UNIQUE NOT NULL, 
ROLES ENUM('customer', 'restaurant_owner', 'driver') NOT NULL,
ACCOUNT_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TEST1 - IF ENUM IS WORKING PROPERLY
INSERT INTO USERS (USER_NAME, PASS_WORD, EMAIL, PHONE, ROLES) 
VALUES ('test_user', 'testpass123', 'test@example.com', '555-1234', 'customer');

INSERT INTO USERS (USER_NAME, PASS_WORD, EMAIL, PHONE, ROLES) 
VALUES ('restaurant_admin', 'adminpass456', 'admin@restaurant.com', '555-5678', 'restaurant_owner');

INSERT INTO USERS (USER_NAME, PASS_WORD, EMAIL, PHONE, ROLES) 
VALUES ('delivery_driver', 'driverpass789', 'driver@delivery.com', '555-9999', 'driver');

SELECT * FROM USERS;

-- DELETE ALL ROWS
TRUNCATE TABLE USERS;

-- TEST2 - SHOULD FAIL DUE TO INCORRECT ENMU
INSERT INTO USERS (USER_NAME, PASS_WORD, EMAIL, PHONE, ROLES) 
VALUES ('bad_role', 'pass789', 'bad@test.com', '555-4444', 'admin');


-- TEST3 - NOT NULL- SHOULD FAIL DUE TO USERNAME BEING NOT NULL 
INSERT INTO USERS (PASS_WORD, EMAIL, PHONE, ROLES) 
VALUES ('pass123', 'missing@test.com', '555-5555', 'customer');

ALTER TABLE USERS AUTO_INCREMENT = 1;
